name: EvokerLootModifier
main: DisableTotems.EvokerLootModifier
version: 2.1
api-version: '26.2'
description: "Replaces Totems of Undying with gold ingots in evoker loot"
author: Arkterion Labs
website: https://arkterion.com